using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ContactBookService.BusinessClasses.Common;
using ContactBookService.CommonComponents;

namespace ContactBookService.CommonComponents.Common
{
    public class CommonFactoy
    {
        static Dictionary<string, ICommon> dict;
        static CommonFactoy()
        {
            dict = new Dictionary<string, ICommon>();

            #region Unplaced Order
            dict.Add("COMPANY_BRANCH_MASTER_GET", new COMPANY_BRANCH_MASTER_GET());
            dict.Add("COMPANY_BRANCH_MASTER_CRUD", new COMPANY_BRANCH_MASTER_CRUD());
            dict.Add("COMPANYMASTER_GET", new COMPANYMASTER_GET());
            dict.Add("COMPANYMASTER_CRUD", new COMPANYMASTER_CRUD());
            dict.Add("GROUP_GET", new GROUP_GET());
            dict.Add("GROUP_CRUD", new GROUP_CRUD());
            dict.Add("MASTER_CITY_STATE_COUNTRY_CRUDOPERATIONS", new MASTER_CITY_STATE_COUNTRY_CRUDOPERATIONS());
            dict.Add("MASTER_COUNTRY_STATE_CITY_GET", new MASTER_COUNTRY_STATE_CITY_GET());
            dict.Add("CONTACT_GET", new CONTACT_GET());
            dict.Add("CONTACT_CRUD", new CONTACT_CRUD());
            dict.Add("LOGIN_AUTHENTICATION", new LOGIN_AUTHENTICATION());
            dict.Add("ANNI_BDAY_NOTIFICATION_GET", new ANNI_BDAY_NOTIFICATION_GET());
            dict.Add("MASTERDESIGN_GET", new MASTERDESIGN_GET());
            dict.Add("MASTERDESIGN_CRUD", new MASTERDESIGN_CRUD());
            dict.Add("SMSDEMO_GET", new SMSDEMO_GET());
            dict.Add("SMSDEMO_CRUDOPERATIONS", new SMSDEMO_CRUDOPERATIONS());
            dict.Add("EMAILDEMO_GET", new EMAILDEMO_GET());
            dict.Add("EMAILDEMO_CRUDOPERATIONS", new EMAILDEMO_CRUDOPERATIONS());
            dict.Add("STICKEY_GET", new STICKEY_GET());
            dict.Add("STATE_COUNTRYWISE_GET", new STATE_COUNTRYWISE_GET());
            dict.Add("BAGLIST_GET", new BAGLIST_GET());
            dict.Add("BAGLIST_CRUD", new BAGLIST_CRUD());
            dict.Add("DESIGNTYPE_GET", new DESIGNTYPE_GET());
            dict.Add("USERDETAILS_CRUD", new USERDETAILS_CRUD());
            dict.Add("USERDETAILS_GET", new USERDETAILS_GET());
            dict.Add("SECURITY_USERACCESSGROUPS_GET", new SECURITY_USERACCESSGROUPS_GET());
            dict.Add("SECURITY_USERACCESSGROUPS_CRUDOPERATIONS", new SECURITY_USERACCESSGROUPS_CRUDOPERATIONS());
            dict.Add("SECURITY_USERPERMISSION_GET", new SECURITY_USERPERMISSION_GET());
            dict.Add("SALES_WHOLESELLER_DETAILS_GET", new SALES_WHOLESELLER_DETAILS_GET());
            dict.Add("SALES_WHOLESELLER_DETAILS_CRUD", new SALES_WHOLESELLER_DETAILS_CRUD());
            dict.Add("SALES_WHOLESELLER_FILES_GET", new SALES_WHOLESELLER_FILES_GET());
            dict.Add("PRIVACY_POLICY_GET", new PRIVACY_POLICY_GET());
            dict.Add("PRIVACY_POLICY_CRUD", new PRIVACY_POLICY_CRUD());
            dict.Add("DESIGN_MASTER_GET", new DESIGN_MASTER_GET());
            dict.Add("DESIGNDETAIL_GET", new DESIGNDETAIL_GET()); 
            dict.Add("MAKING_PRICELIST_GET", new MAKING_PRICELIST_GET()); 
            dict.Add("PRICELIST_GET", new PRICELIST_GET());
            dict.Add("GOLD_DETAILS_GET", new GOLD_DETAILS_GET());
            dict.Add("GOLD_DETAILS_CRUD", new GOLD_DETAILS_CRUD());
            dict.Add("APP_WOMAN_COLLECTION_GET", new APP_WOMAN_COLLECTION_GET());
            dict.Add("APP_WOMAN_COLLECTION_CRUD", new APP_WOMAN_COLLECTION_CRUD());
            dict.Add("CATEGORY_GET", new CATEGORY_GET()); 
            dict.Add("SUBCATEGORY_GET", new SUBCATEGORY_GET()); 
            dict.Add("SUBCATEGORY_CRUD", new SUBCATEGORY_CRUD());
            dict.Add("BUSINESS_POLICY_GET", new BUSINESS_POLICY_GET());
            dict.Add("ALLOW_IP_LIST_GET", new ALLOW_IP_LIST_GET());
            dict.Add("ALLOW_IP_LIST_CRUD", new ALLOW_IP_LIST_CRUD()); 
            dict.Add("SECURITY_MENU_GET", new SECURITY_MENU_GET());
            dict.Add("APP_LOGIN_AUTHENTICATION", new APP_LOGIN_AUTHENTICATION());
            dict.Add("APP_CATEGORY_DESIGN_MASTER_GET", new APP_CATEGORY_DESIGN_MASTER_GET());
            dict.Add("APP_CATEGORY_DESIGN_DETAIL_GET", new APP_CATEGORY_DESIGN_DETAIL_GET());
            dict.Add("APP_CATEGORY_SHARED_DESIGN_DETAIL_GET", new APP_CATEGORY_SHARED_DESIGN_DETAIL_GET());
            dict.Add("LATEST_GOLDRATE_GET", new LATEST_GOLDRATE_GET());
            dict.Add("SHOPPINGCART_CRUD", new SHOPPINGCART_CRUD());
            dict.Add("SHOPPINGCART_GET", new SHOPPINGCART_GET());
            dict.Add("APP_USERPROFILE_GET", new APP_USERPROFILE_GET());
            dict.Add("SALES_QUOTATION_CRUD", new SALES_QUOTATION_CRUD());
            dict.Add("WISHLIST_GET", new WISHLIST_GET());
            dict.Add("SALES_QUOTATION_HISTORY_GET", new SALES_QUOTATION_HISTORY_GET());
            dict.Add("SALES_QUOTATION_DETAIL_GET", new SALES_QUOTATION_DETAIL_GET());
            dict.Add("APP_CONTRY_STATE_CITY_GET", new APP_CONTRY_STATE_CITY_GET());
            dict.Add("FEEDBACK_GET", new FEEDBACK_GET());
            dict.Add("FEEDBACK_CRUD", new FEEDBACK_CRUD());
            dict.Add("SECURITY_USER_FORGOTPASSWORD", new SECURITY_USER_FORGOTPASSWORD()); 
            dict.Add("SALES_QUOTATION_LIST_GET", new SALES_QUOTATION_LIST_GET());
            dict.Add("SALES_QUOTATION_DESIGN_ITEM_GET", new SALES_QUOTATION_DESIGN_ITEM_GET());
            dict.Add("CART_ITEM_COUNT_GET", new CART_ITEM_COUNT_GET());
            dict.Add("COMMON_CONTACT_ABOUTMAS_DATA_GET", new COMMON_CONTACT_ABOUTMAS_DATA_GET()); 
            dict.Add("ACTIVITYLOCATIONDETAIL_GET", new ACTIVITYLOCATIONDETAIL_GET()); 
            dict.Add("APP_DESIGN_FILES_GET", new APP_DESIGN_FILES_GET());
            dict.Add("CHARNI_MASTER_GET", new CHARNI_MASTER_GET()); 
            dict.Add("APP_CUSTOMIZE_MASTER_GET", new APP_CUSTOMIZE_MASTER_GET()); 
            dict.Add("HOMEBOTTOMSLIDER_GET", new HOMEBOTTOMSLIDER_GET());
            dict.Add("HOMEBOTTOMSLIDER_CRUD", new HOMEBOTTOMSLIDER_CRUD());
            dict.Add("ANNOUNCEMENT_GET", new ANNOUNCEMENT_GET());
            dict.Add("MAIN_LETTER_TEMPLATE_GET", new MAIN_LETTER_TEMPLATE_GET());
            dict.Add("MAIN_LETTER_TEMPLATE_CRUD", new MAIN_LETTER_TEMPLATE_CRUD());
            dict.Add("MAIN_LETTERTYPE_GET", new MAIN_LETTERTYPE_GET()); 
            dict.Add("ANNOUNCEMENT_CRUD", new ANNOUNCEMENT_CRUD());
            dict.Add("DATA_MIGRATION_ERP_TO_TRINITY", new DATA_MIGRATION_ERP_TO_TRINITY());
            dict.Add("MAIN_LETTERTEMPLATEIMAGE_GET", new MAIN_LETTERTEMPLATEIMAGE_GET());
            dict.Add("MAIN_LETTERTEMPLATEIMAGE_CRUD", new MAIN_LETTERTEMPLATEIMAGE_CRUD());
            dict.Add("DATAMIGRATE_GET", new DATAMIGRATE_GET());
            dict.Add("CONTACTUS_GET", new CONTACTUS_GET());
            dict.Add("CONTACTUS_CRUD", new CONTACTUS_CRUD());
            dict.Add("EMAILNOTIFICATION_GET", new EMAILNOTIFICATION_GET());
            dict.Add("EMAILNOTIFICATION_CRUD", new EMAILNOTIFICATION_CRUD());
            dict.Add("NEWLETTER_CRUD", new NEWLETTER_CRUD());
            dict.Add("EMAILDEMOIMAGE_GET", new EMAILDEMOIMAGE_GET());
            dict.Add("EMAILDEMOIMAGE_CRUD", new EMAILDEMOIMAGE_CRUD());
            dict.Add("SITEMAP_GET", new SITEMAP_GET());
            dict.Add("EMAILSERVER_SETTINGS_CRUD", new EMAILSERVER_SETTINGS_CRUD());
            dict.Add("EMAILSERVER_SETTINGS_GET", new EMAILSERVER_SETTINGS_GET());
            dict.Add("EMAILDEMO_PUBLISH", new EMAILDEMO_PUBLISH());
            dict.Add("EMAILDEMO_PUBLISH_HISTORY_GET", new EMAILDEMO_PUBLISH_HISTORY_GET());
            dict.Add("SMSDEMO_PUBLISH", new SMSDEMO_PUBLISH());            
            dict.Add("SMSPUBLISH", new SMSPUBLISH());            
            dict.Add("SMSSENT_RESPONSE_CRUD", new SMSSENT_RESPONSE_CRUD());
            dict.Add("SMSDEMO_PUBLISH_HISTORY_GET", new SMSDEMO_PUBLISH_HISTORY_GET());
            dict.Add("SMSSENTLIST_GET", new SMSSENTLIST_GET());
            dict.Add("EMAILSENTLIST_GET", new EMAILSENTLIST_GET());
            dict.Add("COMMON_CHARTQUERY_CRUD", new COMMON_CHARTQUERY_CRUD());
            dict.Add("COMMON_CHARTQUERY_GET", new COMMON_CHARTQUERY_GET());
            dict.Add("COMMON_CHARTFIELDLIST_CRUD", new COMMON_CHARTFIELDLIST_CRUD());
            dict.Add("COMMON_CHARTFIELDLIST_GET", new COMMON_CHARTFIELDLIST_GET());
            dict.Add("COMMON_CHARTDESIGN_CRUD", new COMMON_CHARTDESIGN_CRUD());
            dict.Add("COMMON_CHARTDESIGN_GET", new COMMON_CHARTDESIGN_GET());
            dict.Add("COMMON_CHARTDESIGNDETAIL_GET", new COMMON_CHARTDESIGNDETAIL_GET());
            dict.Add("SECURITY_CHARTSPERMISSION_GET", new SECURITY_CHARTSPERMISSION_GET());
            dict.Add("COMMON_PERMISSIONWISE_CHARTLIST_GET", new COMMON_PERMISSIONWISE_CHARTLIST_GET());
            dict.Add("COMMON_CHARTFILTERFIELD_GET", new COMMON_CHARTFILTERFIELD_GET());
            dict.Add("COMMON_CHART_FILTERCRITERIA_CRUDOPERATIONS", new COMMON_CHART_FILTERCRITERIA_CRUDOPERATIONS());
            dict.Add("COMMON_CHART_FILTERCRITERIA_GET", new COMMON_CHART_FILTERCRITERIA_GET());
            dict.Add("COMMON_CHARTDATA_GET", new COMMON_CHARTDATA_GET());
            dict.Add("COMMON_USER_CHARTVIEWERSETTING_CRUD", new COMMON_USER_CHARTVIEWERSETTING_CRUD());
            dict.Add("STATIC_CONCEPTOF_MAS_GET", new STATIC_CONCEPTOF_MAS_GET());
            dict.Add("ADMINNOTIFICATION_MASTER_GET", new ADMINNOTIFICATION_MASTER_GET());
            dict.Add("ADMINNOTIFICATION_MASTER_CRUD", new ADMINNOTIFICATION_MASTER_CRUD());
            dict.Add("CURRENCY_EXCHANGERATE_DETAILS_CRUD", new CURRENCY_EXCHANGERATE_DETAILS_CRUD());
            dict.Add("CURRENCY_EXCHANGERATE_DETAILS_GET", new CURRENCY_EXCHANGERATE_DETAILS_GET());
            dict.Add("B2C_CURRENCYWISE_CHARGES_CRUD", new B2C_CURRENCYWISE_CHARGES_CRUD());
            dict.Add("B2C_CURRENCYWISE_CHARGES_GET", new B2C_CURRENCYWISE_CHARGES_GET());
            dict.Add("NEW_DESIGN_DAYS_GET", new NEW_DESIGN_DAYS_GET());
            dict.Add("NEW_DESIGN_DAYS_CRUD", new NEW_DESIGN_DAYS_CRUD());
            dict.Add("USERLOGINHISTORY_GET", new USERLOGINHISTORY_GET());
            dict.Add("LOGOUTMASTER_CRUD", new LOGOUTMASTER_CRUD());

            dict.Add("ACC_PARTYCOMMITMENTDETAILS_CRUD", new ACC_PARTYCOMMITMENTDETAILS_CRUD());
            dict.Add("ACC_PARTYCOMMITMENTDETAILS_GET", new ACC_PARTYCOMMITMENTDETAILS_GET());
            dict.Add("ACC_OUTSTANDING_REPORT_CASHBANK_DETAILS_GET", new ACC_OUTSTANDING_REPORT_CASHBANK_DETAILS_GET());
            dict.Add("ACC_PROFITANDLOSS_REPORT_GET", new ACC_PROFITANDLOSS_REPORT_GET());
            dict.Add("ACC_TRAILBALANCE_REPORT_GET", new ACC_TRAILBALANCE_REPORT_GET());


            #endregion

            #region "Outlet Module"

            dict.Add("OUTLET_EMPLOYEE_DETAILS_CRUD", new OUTLET_EMPLOYEE_DETAILS_CRUD());
            dict.Add("OUTLET_EMPLOYEE_DETAILS_GET", new OUTLET_EMPLOYEE_DETAILS_GET());
            dict.Add("OUTLET_MASTER_DETAILS_GET", new OUTLET_MASTER_DETAILS_GET());
            dict.Add("OUTLET_MASTER_DETAILS_CRUD", new OUTLET_MASTER_DETAILS_CRUD());
            dict.Add("OUTLET_ACCOUNT_YEAR_MASTER_CRUD", new OUTLET_ACCOUNT_YEAR_MASTER_CRUD());
            dict.Add("OUTLET_ACCOUNT_YEAR_MASTER_GET", new OUTLET_ACCOUNT_YEAR_MASTER_GET());
            dict.Add("OUTLET_HEAD_DATA_GET", new OUTLET_HEAD_DATA_GET());
            dict.Add("OUTLET_HEAD_MASTER_CRUD", new OUTLET_HEAD_MASTER_CRUD());
            dict.Add("OUTLET_SUPER_ADMIN_DETAILS_CRUD", new OUTLET_SUPER_ADMIN_DETAILS_CRUD());
            dict.Add("OUTLET_SUPER_ADMIN_DETAILS_GET", new OUTLET_SUPER_ADMIN_DETAILS_GET());
            dict.Add("OUTLET_SECURITY_USERLOGIN_AUTHENTICATION", new OUTLET_SECURITY_USERLOGIN_AUTHENTICATION());
            dict.Add("OUTLET_SECURITY_USERACCESSGROUPS_CRUDOPERATIONS", new OUTLET_SECURITY_USERACCESSGROUPS_CRUDOPERATIONS());
            dict.Add("OUTLET_SECURITY_USERPERMISSION_GET", new OUTLET_SECURITY_USERPERMISSION_GET());
            dict.Add("OUTLET_SECURITY_USERACCESSGROUPS_GET", new OUTLET_SECURITY_USERACCESSGROUPS_GET());
            dict.Add("OUTLET_SECURITY_USER_FORGOTPASSWORD", new OUTLET_SECURITY_USER_FORGOTPASSWORD());
            dict.Add("OUTLET_EMP_ACCOUNTYEAR_MAPPING_CRUD", new OUTLET_EMP_ACCOUNTYEAR_MAPPING_CRUD());
            dict.Add("OUTLET_OUTLET_GSTRATEMASTER_CRUD", new OUTLET_OUTLET_GSTRATEMASTER_CRUD());
            dict.Add("OUTLET_OUTLET_GSTRATEMASTER_GET", new OUTLET_OUTLET_GSTRATEMASTER_GET());
            dict.Add("OUTLET_PRICE_LIST_SETTINGS_CRUD", new OUTLET_PRICE_LIST_SETTINGS_CRUD());
            dict.Add("OUTLET_PRICE_LIST_SETTINGS_GET", new OUTLET_PRICE_LIST_SETTINGS_GET());
            dict.Add("OUTLET_LABOUR_CHARGE_MASTER_GET", new OUTLET_LABOUR_CHARGE_MASTER_GET());
            dict.Add("OUTLET_LABOUR_CHARGE_MASTER_CRUD", new OUTLET_LABOUR_CHARGE_MASTER_CRUD());
            dict.Add("OUTLET_LABOUR_CHARGE_MASTERHIS_GET", new OUTLET_LABOUR_CHARGE_MASTERHIS_GET());
            dict.Add("OUTLET_DIAMOND_RATE_MASTER_GET", new OUTLET_DIAMOND_RATE_MASTER_GET());
            dict.Add("OUTLET_DIAMOND_RATE_MASTER_CRUD", new OUTLET_DIAMOND_RATE_MASTER_CRUD());
            dict.Add("OUTLET_SHAPE_SIZE_COLOR_GET", new OUTLET_SHAPE_SIZE_COLOR_GET());
            dict.Add("OUTLET_ACCOUNT_MASTER_GET", new OUTLET_ACCOUNT_MASTER_GET());
            dict.Add("OUTLET_ACCOUNT_MASTER_CRUD", new OUTLET_ACCOUNT_MASTER_CRUD());
            dict.Add("OUTLET_ACCOUNT_MASTER_DOCUMENT_GET", new OUTLET_ACCOUNT_MASTER_DOCUMENT_GET());
            dict.Add("OUTLET_PURCHASE_MASTER_CRUD", new OUTLET_PURCHASE_MASTER_CRUD());
            dict.Add("OUTLET_PURCHASE_MASTER_DETAIL_CRUD", new OUTLET_PURCHASE_MASTER_DETAIL_CRUD());
            dict.Add("OUTLET_PURCHASE_MASTER_GET", new OUTLET_PURCHASE_MASTER_GET());
            dict.Add("OUTLET_PRODUCT_MASTER_GET", new OUTLET_PRODUCT_MASTER_GET());
            dict.Add("OUTLET_PRODUCT_MASTER_DETAIL_GET", new OUTLET_PRODUCT_MASTER_DETAIL_GET());
            dict.Add("OUTLET_DESIGNNO_COPYTODETAIL_CRUD", new OUTLET_DESIGNNO_COPYTODETAIL_CRUD());
            dict.Add("OUTLET_PURCHASE_FINAL_SUBMIT_CRUD", new OUTLET_PURCHASE_FINAL_SUBMIT_CRUD());
            dict.Add("OUTLET_CHARNI_MASTER_AUTOSUGGEST", new OUTLET_CHARNI_MASTER_AUTOSUGGEST());
            dict.Add("OUTLET_PURCHASE_PAYMENT_TERMS_GET", new OUTLET_PURCHASE_PAYMENT_TERMS_GET());
            dict.Add("OUTLET_PURCHASE_PAYMENT_TERMS_CRUD", new OUTLET_PURCHASE_PAYMENT_TERMS_CRUD());
            dict.Add("OUTLET_CATEGORY_SIZE_MASTER_AUTOSUGGEST", new OUTLET_CATEGORY_SIZE_MASTER_AUTOSUGGEST());
            dict.Add("OUTLET_CASHBANKBOOK_GET", new OUTLET_CASHBANKBOOK_GET());
            dict.Add("OUTLET_CASHBANKBOOK_CRUD", new OUTLET_CASHBANKBOOK_CRUD());
            dict.Add("OUTLET_CASHBANKBOOK_DETAIL_GET", new OUTLET_CASHBANKBOOK_DETAIL_GET());
            dict.Add("OUTLET_TEMP_TRANSFER_COPYTODETAIL_CRUD", new OUTLET_TEMP_TRANSFER_COPYTODETAIL_CRUD());
            dict.Add("OUTLET_STOCK_MASTER_GET", new OUTLET_STOCK_MASTER_GET());
            dict.Add("OUTLET_PENDING_RECEIVER_BILL_LIST_GET", new OUTLET_PENDING_RECEIVER_BILL_LIST_GET());
            dict.Add("OUTLET_STOCKINWARD_FINAL_SUBMIT_CRUD", new OUTLET_STOCKINWARD_FINAL_SUBMIT_CRUD());
            dict.Add("OUTLET_LEDGER_REPORT_GET", new OUTLET_LEDGER_REPORT_GET());
            dict.Add("OUTLET_STOCK_TRANSFER_BILLNO_AUTOSUGGEST", new OUTLET_STOCK_TRANSFER_BILLNO_AUTOSUGGEST());
            dict.Add("OUTLET_SIZE_MASTER_AUTOSUGGEST", new OUTLET_SIZE_MASTER_AUTOSUGGEST());
            dict.Add("OUTLET_CASTOBANK_TRANSACTION_CRUD", new OUTLET_CASTOBANK_TRANSACTION_CRUD());
            dict.Add("OUTLET_CASTOBANK_TRANSACTION_GET", new OUTLET_CASTOBANK_TRANSACTION_GET());
            dict.Add("OUTLET_SALES_RETURN_MASTER_CRUD", new OUTLET_SALES_RETURN_MASTER_CRUD());
            dict.Add("OUTLET_SALES_RETURN_PRODUCT_MASTER_GET", new OUTLET_SALES_RETURN_PRODUCT_MASTER_GET());
            dict.Add("OUTLET_SALES_RETURN_MASTER_GET", new OUTLET_SALES_RETURN_MASTER_GET());
            dict.Add("OUTLET_SALES_RETURN_FINAL_SUBMIT_CRUD", new OUTLET_SALES_RETURN_FINAL_SUBMIT_CRUD());
            dict.Add("OUTLET_SALES_RETURN_COPYTODETAIL_CRUD", new OUTLET_SALES_RETURN_COPYTODETAIL_CRUD());

            dict.Add("OUTLET_SALES_RETURN_PRODUCT_DETAIL_GET", new OUTLET_SALES_RETURN_PRODUCT_DETAIL_GET());
            dict.Add("OUTLET_SALES_RETURN_PAYMENT_TERMS_GET", new OUTLET_SALES_RETURN_PAYMENT_TERMS_GET());
            dict.Add("OUTLET_SALES_RETURN_PAYMENT_TERMS_CRUD", new OUTLET_SALES_RETURN_PAYMENT_TERMS_CRUD());

            dict.Add("OUTLET_STOCKRETURN_FINAL_SUBMIT_CRUD", new OUTLET_STOCKRETURN_FINAL_SUBMIT_CRUD());
            dict.Add("OUTLET_STOCKRETURN_MASTER_GET", new OUTLET_STOCKRETURN_MASTER_GET());
            dict.Add("OUTLET_STOCKRETURN_PRODUCT_MASTER_GET", new OUTLET_STOCKRETURN_PRODUCT_MASTER_GET());
            dict.Add("OUTLET_STOCKRETURN_PRODUCT_DETAIL_GET", new OUTLET_STOCKRETURN_PRODUCT_DETAIL_GET());
            dict.Add("OUTLET_STOCK_RETURN_COPYTODETAIL_CRUD", new OUTLET_STOCK_RETURN_COPYTODETAIL_CRUD());
            dict.Add("OUTLET_STOCK_RETURN_BAGNO_AUTOSUGGEST", new OUTLET_STOCK_RETURN_BAGNO_AUTOSUGGEST());
            
            dict.Add("OUTLET_INVOICESETTING_CRUD", new OUTLET_INVOICESETTING_CRUD());
            dict.Add("OUTLET_INVOICESETTING_GET", new OUTLET_INVOICESETTING_GET());

            dict.Add("ACC_OPENINGASSETS_CRUD", new ACC_OPENINGASSETS_CRUD());
            dict.Add("ACC_OPENINGASSETS_GET", new ACC_OPENINGASSETS_GET());
            dict.Add("ACC_OPENINGASSETS_DETAIL_GET", new ACC_OPENINGASSETS_DETAIL_GET());
            dict.Add("ACC_OPENINGASSETS_FILES_GET", new ACC_OPENINGASSETS_FILES_GET());

            /*---Sales Entry--------------------------------------------------------------------------------------------*/
            dict.Add("OUTLET_SALES_MASTER_CRUD", new OUTLET_SALES_MASTER_CRUD());
            dict.Add("OUTLET_SALES_MASTER_GET", new OUTLET_SALES_MASTER_GET());
            dict.Add("OUTLET_SALESPRODUCT_MASTER_DETAIL_GET", new OUTLET_SALESPRODUCT_MASTER_DETAIL_GET());
            dict.Add("OUTLET_SALESPRODUCT_MASTER_GET", new OUTLET_SALESPRODUCT_MASTER_GET());
            dict.Add("OUTLET_COPYDESIGNNO_TOSALESDETAIL_CRUD", new OUTLET_COPYDESIGNNO_TOSALESDETAIL_CRUD());
            dict.Add("OUTLET_SALES_PRODUCTMASTER_DETAIL_CRUD", new OUTLET_SALES_PRODUCTMASTER_DETAIL_CRUD());
            dict.Add("OUTLET_SALES_FINAL_SUBMIT_CRUD", new OUTLET_SALES_FINAL_SUBMIT_CRUD());
            dict.Add("OUTLET_SALESINVOICE_SUMMARY_GET", new OUTLET_SALESINVOICE_SUMMARY_GET());
            dict.Add("OUTLET_SALESINVOICE_DETAIL_GET", new OUTLET_SALESINVOICE_DETAIL_GET());
            dict.Add("OUTLET_SALESPAYMENT_GET", new OUTLET_SALESPAYMENT_GET());
            dict.Add("OUTLET_SALESPAYMENT_CRUD", new OUTLET_SALESPAYMENT_CRUD());
            dict.Add("OUTLET_BAGNO_SKUNO_AUTOSUGGEST", new OUTLET_BAGNO_SKUNO_AUTOSUGGEST());
            dict.Add("OUTLET_COPYDESIGNNO_TOSALESORDERDETAIL_CRUD", new OUTLET_COPYDESIGNNO_TOSALESORDERDETAIL_CRUD());
            dict.Add("OUTLET_SALESORDER_SUMMARY_GET", new OUTLET_SALESORDER_SUMMARY_GET());
            dict.Add("OUTLET_SALESORDER_SUMMARY_CRUD", new OUTLET_SALESORDER_SUMMARY_CRUD());
            dict.Add("OUTLET_SALESORDERPRODUCT_MASTER_GET", new OUTLET_SALESORDERPRODUCT_MASTER_GET());
            dict.Add("OUTLET_SALESORDERPRODUCT_DETAIL_GET", new OUTLET_SALESORDERPRODUCT_DETAIL_GET());
            dict.Add("OUTLET_SALESORDER_PRODUCTDETAIL_CRUD", new OUTLET_SALESORDER_PRODUCTDETAIL_CRUD());
            dict.Add("OUTLET_SALESORDER_FINAL_SUBMIT_CRUD", new OUTLET_SALESORDER_FINAL_SUBMIT_CRUD());
            dict.Add("OUTLET_SALESORDERPAYMENT_GET", new OUTLET_SALESORDERPAYMENT_GET());
            dict.Add("OUTLET_SALESORDERPAYMENT_CRUD", new OUTLET_SALESORDERPAYMENT_CRUD());
            dict.Add("OUTLET_SALES_MASTER_ACCOUNTID_GET", new OUTLET_SALES_MASTER_ACCOUNTID_GET());
            /*-----------------------------------------------------------------------------------------------*/

            /*---Purchase Return--------------------------------------------------------------------------------------------*/
            dict.Add("OUTLET_SALESPURCHASE_ACCOUNT_AUTOSUGGEST", new OUTLET_SALESPURCHASE_ACCOUNT_AUTOSUGGEST());
            dict.Add("OUTLET_PURCHASERETURN_MASTER_CRUD", new OUTLET_PURCHASERETURN_MASTER_CRUD());
            dict.Add("OUTLET_PURCHASERETURN_MASTER_GET", new OUTLET_PURCHASERETURN_MASTER_GET());
            dict.Add("OUTLET_PURCHASERETURNPRODUCT_MASTER_DETAIL_GET", new OUTLET_PURCHASERETURNPRODUCT_MASTER_DETAIL_GET());
            dict.Add("OUTLET_PURCHASERETURNPRODUCT_MASTER_GET", new OUTLET_PURCHASERETURNPRODUCT_MASTER_GET());
            dict.Add("OUTLET_COPYDESIGNNO_TOPURCHASERETURNDETAIL_CRUD", new OUTLET_COPYDESIGNNO_TOPURCHASERETURNDETAIL_CRUD());            
            dict.Add("OUTLET_PURCHASERETURN_FINAL_SUBMIT_CRUD", new OUTLET_PURCHASERETURN_FINAL_SUBMIT_CRUD());
            dict.Add("OUTLET_PURCHASERETURNPAYMENT_GET", new OUTLET_PURCHASERETURNPAYMENT_GET());
            dict.Add("OUTLET_PURCHASERETURNPAYMENT_CRUD", new OUTLET_PURCHASERETURNPAYMENT_CRUD());
            dict.Add("OUTLET_PURCHASERETURNINVOICE_SUMMARY_GET", new OUTLET_PURCHASERETURNINVOICE_SUMMARY_GET());
            dict.Add("OUTLET_PURCHASERETURNINVOICE_DETAIL_GET", new OUTLET_PURCHASERETURNINVOICE_DETAIL_GET());
            dict.Add("OUTLET_DESIGNLIST_FROMBILLNO_GET", new OUTLET_DESIGNLIST_FROMBILLNO_GET());
            /*-----------------------------------------------------------------------------------------------*/

            dict.Add("OUTLET_GENERAL_PURCHASE_MASTER_GET", new OUTLET_GENERAL_PURCHASE_MASTER_GET());
            dict.Add("OUTLET_GENERAL_PURCHASE_DETAIL_GET", new OUTLET_GENERAL_PURCHASE_DETAIL_GET());
            dict.Add("OUTLET_GENERAL_PURCHASE_MASTER_DETAIL_CRUD", new OUTLET_GENERAL_PURCHASE_MASTER_DETAIL_CRUD());
            dict.Add("OUTLET_JOURNAL_MASTER_GET", new OUTLET_JOURNAL_MASTER_GET());
            dict.Add("OUTLET_JOURNAL_MASTER_CRUD", new OUTLET_JOURNAL_MASTER_CRUD());
            dict.Add("OUTLET_OFFERS_MASTER_GET", new OUTLET_OFFERS_MASTER_GET());
            dict.Add("OUTLET_OFFERS_MASTER_CRUD", new OUTLET_OFFERS_MASTER_CRUD());
            dict.Add("OUTLET_OFFERDESIGNPRICE_GET", new OUTLET_OFFERDESIGNPRICE_GET());
            dict.Add("OUTLET_MATERIAL_PURCHASE_SALES_GET", new OUTLET_MATERIAL_PURCHASE_SALES_GET());
            dict.Add("OUTLET_MATERIAL_PURCHASE_SALES_DETAIL_GET", new OUTLET_MATERIAL_PURCHASE_SALES_DETAIL_GET());
            dict.Add("OUTLET_MATERIAL_PURCHASE_SALES_MASTER_DETAIL_CRUD", new OUTLET_MATERIAL_PURCHASE_SALES_MASTER_DETAIL_CRUD());
            dict.Add("OUTLET_ACCOUNT_BALANCEMAS_GET", new OUTLET_ACCOUNT_BALANCEMAS_GET());
            dict.Add("ACC_ACCOUNT_OPENING_BALANCE_GET", new ACC_ACCOUNT_OPENING_BALANCE_GET());
            
            dict.Add("OUTLET_ACCOUNT_BALANCEMAS_CRUD", new OUTLET_ACCOUNT_BALANCEMAS_CRUD());
            dict.Add("OUTLET_STOCK_REPORT_GET", new OUTLET_STOCK_REPORT_GET());
            dict.Add("OUTLET_STOCKTALLYDETAIL_GET", new OUTLET_STOCKTALLYDETAIL_GET());
            dict.Add("OUTLET_STOCKTALLYDETAIL_CRUD", new OUTLET_STOCKTALLYDETAIL_CRUD());
            dict.Add("OUTLET_STOCKTALLYSUMMARY_GET", new OUTLET_STOCKTALLYSUMMARY_GET());
            dict.Add("OUTLET_GST_REPORT_GET", new OUTLET_GST_REPORT_GET());
            dict.Add("OUTLET_SALES_REPORT_GET", new OUTLET_SALES_REPORT_GET());
            dict.Add("OUTLET_PURCHASE_SALES_REPORT_GET", new OUTLET_PURCHASE_SALES_REPORT_GET());
            dict.Add("OUTLET_MATERIAL_STOCK_REPORT_GET", new OUTLET_MATERIAL_STOCK_REPORT_GET());
            dict.Add("OUTLET_PROFIT_LOSS_ACCOUNT_REPORT_GET", new OUTLET_PROFIT_LOSS_ACCOUNT_REPORT_GET());

            /*---Year End Process--------------------------------------------------------------------------------------------*/
            dict.Add("OUTLET_YEARENDPROCESS", new OUTLET_YEARENDPROCESS());            
            dict.Add("OUTLET_YEARENDPROCESS_ACCOUNTLIST_GET", new OUTLET_YEARENDPROCESS_ACCOUNTLIST_GET());
            dict.Add("OUTLET_YEAREND_ACCOUNTOPENING_CRUD", new OUTLET_YEAREND_ACCOUNTOPENING_CRUD());
            dict.Add("OUTLET_YEARENDPROCESS_STOCKTRANSFER_CRUD", new OUTLET_YEARENDPROCESS_STOCKTRANSFER_CRUD());
            dict.Add("OUTLET_YEARENDPROCESS_GET", new OUTLET_YEARENDPROCESS_GET());
            dict.Add("OUTLET_ACCOUNTYEAR_CLOSEPERIOD_GET", new OUTLET_ACCOUNTYEAR_CLOSEPERIOD_GET());            
            dict.Add("OUTLET_ACCOUNTYEAR_CLOSEPERIOD_CRUD", new OUTLET_ACCOUNTYEAR_CLOSEPERIOD_CRUD());
            /*-----------------------------------------------------------------------------------------------*/

            #endregion

            #region "B2C Module"

            dict.Add("B2C_FESTIVALCOLLECTION_GET", new B2C_FESTIVALCOLLECTION_GET());
            dict.Add("B2C_FESTIVAL_COLLECTION_CRUD", new B2C_FESTIVAL_COLLECTION_CRUD());
            dict.Add("B2C_COLLECTION_GET", new B2C_COLLECTION_GET());
            dict.Add("B2C_COLLECTION_CRUD", new B2C_COLLECTION_CRUD());
            dict.Add("B2C_OFFERS_GET", new B2C_OFFERS_GET());
            dict.Add("B2C_OFFERS_CRUD", new B2C_OFFERS_CRUD());
            dict.Add("B2C_PRODUCT_LISTING_ADS_GET", new B2C_PRODUCT_LISTING_ADS_GET());
            dict.Add("B2C_PRODUCT_LISTING_ADS_CRUD", new B2C_PRODUCT_LISTING_ADS_CRUD());
            dict.Add("B2C_TESTIMONIAL_GET", new B2C_TESTIMONIAL_GET());
            dict.Add("B2C_TESTIMONIAL_CRUD", new B2C_TESTIMONIAL_CRUD());
            dict.Add("B2C_CART_GET", new B2C_CART_GET());
            dict.Add("B2C_CART_CRUD", new B2C_CART_CRUD());
            dict.Add("B2C_WISHLIST_GET", new B2C_WISHLIST_GET());
            dict.Add("B2C_WISHLIST_CRUD", new B2C_WISHLIST_CRUD());
            dict.Add("B2C_CUSTOMERDETAILS_GET", new B2C_CUSTOMERDETAILS_GET());
            dict.Add("B2C_CUSTOMERDETAILS_CRUD", new B2C_CUSTOMERDETAILS_CRUD());
            dict.Add("B2C_LOGIN_AUTHENTICATION", new B2C_LOGIN_AUTHENTICATION());
            dict.Add("B2C_PRODUCT_DESIGN_MASTER_GET", new B2C_PRODUCT_DESIGN_MASTER_GET());
            dict.Add("B2C_PRODUCT_DESIGN_DETAIL_GET", new B2C_PRODUCT_DESIGN_DETAIL_GET());
            dict.Add("B2C_MENULIST", new B2C_MENULIST());
            dict.Add("B2C_SECURITY_USER_FORGOTPASSWORD", new B2C_SECURITY_USER_FORGOTPASSWORD());
            dict.Add("B2C_ERROR_CRUD", new B2C_ERROR_CRUD());
            dict.Add("B2C_ERROR_GET", new B2C_ERROR_GET());
            dict.Add("B2C_FILTER_GET", new B2C_FILTER_GET());
            dict.Add("B2C_SEARCHHISTORY_GET", new B2C_SEARCHHISTORY_GET());
            dict.Add("B2C_CUSTOMIZE_MASTER_GET", new B2C_CUSTOMIZE_MASTER_GET());
            dict.Add("B2C_DOPAYMENT", new B2C_DOPAYMENT());
            dict.Add("B2C_SHIPPINGADDRESSDETAILS_GET", new B2C_SHIPPINGADDRESSDETAILS_GET());
            dict.Add("B2C_SHIPPINGADDRESSDETAILS_CRUD", new B2C_SHIPPINGADDRESSDETAILS_CRUD());
            dict.Add("B2C_ORDER_CRUD", new B2C_ORDER_CRUD());
            dict.Add("B2C_SEARCHHISTORY_CRUD", new B2C_SEARCHHISTORY_CRUD());
            dict.Add("B2C_CART_WISH_COUNT_GET", new B2C_CART_WISH_COUNT_GET());
            dict.Add("GETANDSAVEPAYMENTDETAIL", new GETANDSAVEPAYMENTDETAIL());
            dict.Add("CANCELORDERDETAILS", new CANCELORDERDETAILS());
            dict.Add("B2C_ORDER_PAYMENT_DETAIL_CRUD", new B2C_ORDER_PAYMENT_DETAIL_CRUD());
            dict.Add("B2C_ORDER_HISTORY_GET", new B2C_ORDER_HISTORY_GET());
            dict.Add("B2C_ORDER_HISTORY_DETAIL_GET", new B2C_ORDER_HISTORY_DETAIL_GET());
            dict.Add("B2C_ORDER_CANCEL_REASON_GET", new B2C_ORDER_CANCEL_REASON_GET());
            dict.Add("B2C_ORDER_CANCEL_SUMMARY_CRUD", new B2C_ORDER_CANCEL_SUMMARY_CRUD());
            dict.Add("B2C_MAIN_ORDERACTION_CRUD", new B2C_MAIN_ORDERACTION_CRUD());
            dict.Add("B2C_APPNOTIFICATION_CRUD", new B2C_APPNOTIFICATION_CRUD());
            dict.Add("B2C_ORDER_TRACKING_CRUD", new B2C_ORDER_TRACKING_CRUD());
            dict.Add("B2C_CITY_GET", new B2C_CITY_GET());
            dict.Add("B2C_NEARESTOUTLET_GET", new B2C_NEARESTOUTLET_GET());
            dict.Add("B2C_CHARGES_SETTINGS_GET", new B2C_CHARGES_SETTINGS_GET());
            dict.Add("B2C_CHARGES_SETTINGS_CRUD", new B2C_CHARGES_SETTINGS_CRUD());
            dict.Add("B2C_DELIVERY_DAYS_GET", new B2C_DELIVERY_DAYS_GET());
            dict.Add("B2C_DELIVERY_DAYS_CRUD", new B2C_DELIVERY_DAYS_CRUD());
            dict.Add("B2C_ORDER_RETURN_REASON_GET", new B2C_ORDER_RETURN_REASON_GET());
            dict.Add("B2C_ORDER_RETURN_SUMMARY_CRUD", new B2C_ORDER_RETURN_SUMMARY_CRUD());
            dict.Add("B2C_MAIN_STATIC_ORDERSTATUS_GET", new B2C_MAIN_STATIC_ORDERSTATUS_GET());
            dict.Add("B2C_MAIN_ORDERACTION_GET", new B2C_MAIN_ORDERACTION_GET());
            dict.Add("B2C_TERMSANDCONDITION_GET", new B2C_TERMSANDCONDITION_GET());
            dict.Add("B2C_PRIVACYPOLICY_GET", new B2C_PRIVACYPOLICY_GET());
            dict.Add("B2C_FAQ_GET", new B2C_FAQ_GET());
            dict.Add("B2C_NOTIFICATION_GET", new B2C_NOTIFICATION_GET());
            dict.Add("B2C_NOTIFICATION_CRUD", new B2C_NOTIFICATION_CRUD());
            dict.Add("B2C_ALL_ORDER_LIST_GET", new B2C_ALL_ORDER_LIST_GET());
            dict.Add("B2C_ORDER_DETAIL_GET", new B2C_ORDER_DETAIL_GET());
            dict.Add("B2C_ORDER_PAYMENT_DETAIL_GET", new B2C_ORDER_PAYMENT_DETAIL_GET());
            dict.Add("B2C_ORDER_CANCEL_REFUND_DETAIL_GET", new B2C_ORDER_CANCEL_REFUND_DETAIL_GET());
            dict.Add("B2C_ORDER_RETURN_REFUND_DETAIL_GET", new B2C_ORDER_RETURN_REFUND_DETAIL_GET());
            dict.Add("B2C_ORDER_CANCEL_REFUND_MASTER_GET", new B2C_ORDER_CANCEL_REFUND_MASTER_GET());
            dict.Add("B2C_ORDER_RETURN_REFUND_MASTER_GET", new B2C_ORDER_RETURN_REFUND_MASTER_GET());
            dict.Add("B2C_ORDER_CANCEL_REFUND_DETAIL_CRUD", new B2C_ORDER_CANCEL_REFUND_DETAIL_CRUD());
            dict.Add("B2C_ORDER_RETURN_REFUND_DETAIL_CRUD", new B2C_ORDER_RETURN_REFUND_DETAIL_CRUD());
            dict.Add("SEND_NOTIFICATION", new SEND_NOTIFICATION());
            dict.Add("B2C_SIGNALNOTIFICATION_GET", new B2C_SIGNALNOTIFICATION_GET());
            dict.Add("B2C_SIGNALNOTIFICATION_CRUD", new B2C_SIGNALNOTIFICATION_CRUD());
            dict.Add("B2C_SIGNALNOTIFICATION_HISTORY_GET", new B2C_SIGNALNOTIFICATION_HISTORY_GET());
            dict.Add("B2C_SIGNALNOTIFICATION_HISTORY_CRUD", new B2C_SIGNALNOTIFICATION_HISTORY_CRUD());
            dict.Add("B2C_BESTSELLINGCATEGORY_GET", new B2C_BESTSELLINGCATEGORY_GET());
            dict.Add("B2C_PRIVACYPOLICY_CRUD", new B2C_PRIVACYPOLICY_CRUD());
            dict.Add("B2C_TERMSANDCONDITION_CRUD", new B2C_TERMSANDCONDITION_CRUD());
            dict.Add("B2C_FAQ_CRUD", new B2C_FAQ_CRUD());



            #endregion

            #region "Radhika Module"

            dict.Add("RADHIKA_CUSTOMER_GET", new RADHIKA_CUSTOMER_GET());
            dict.Add("RADHIKA_CUSTOMER_CRUD", new RADHIKA_CUSTOMER_CRUD());

            #endregion


            dict.Add("APP_ENCRYPT_DESIGNCODE", new APP_ENCRYPT_DESIGNCODE());

            #region "Manufacturing"

            dict.Add("GOLD_EXCHANGERATE_DETAILS_GET", new GOLD_EXCHANGERATE_DETAILS_GET());


            dict.Add("ACC_BALANCE_GET", new ACC_BALANCE_GET());
            dict.Add("ACC_LEDGER_REPORT_GET", new ACC_LEDGER_REPORT_GET());
            dict.Add("ACC_LEDGER_REPORT_DETAILS_GET", new ACC_LEDGER_REPORT_DETAILS_GET());
            dict.Add("ACC_OUTSTANDING_REPORT_GET", new ACC_OUTSTANDING_REPORT_GET());
            dict.Add("ACC_OUTSTANDING_REPORT_DETAILS_GET", new ACC_OUTSTANDING_REPORT_DETAILS_GET());
            dict.Add("ACC_ACCOUNTOPENINGBALANCE_DETAILS_GET", new ACC_ACCOUNTOPENINGBALANCE_DETAILS_GET());
            dict.Add("ACC_BALANCESHEET_REPORT_GET", new ACC_BALANCESHEET_REPORT_GET());


            dict.Add("STATIC_MASTER_GET", new STATIC_MASTER_GET());
            dict.Add("STATIC_MASTER_MULTIPLE_GET", new STATIC_MASTER_MULTIPLE_GET());

            dict.Add("USER_CURRENTACCOUNTYEAR_CRUD", new USER_CURRENTACCOUNTYEAR_CRUD());
            dict.Add("PRD_DESIGN_MASTER_GET", new PRD_DESIGN_MASTER_GET());
            dict.Add("PRD_DESIGN_MASTER_CRUD", new PRD_DESIGN_MASTER_CRUD());
            dict.Add("PRD_DESIGN_DETAIL_GET", new PRD_DESIGN_DETAIL_GET());
            dict.Add("PRD_DESIGN_IMAGES_GET", new PRD_DESIGN_IMAGES_GET());
            dict.Add("PRD_SELECTIONLIST_CRUD", new PRD_SELECTIONLIST_CRUD());
            dict.Add("PRD_SELECTIONLIST_GET", new PRD_SELECTIONLIST_GET());
            dict.Add("PRD_SELECTIONLIST_ITEMS_GET", new PRD_SELECTIONLIST_ITEMS_GET());
            dict.Add("PRD_DESIGNSHARING_CRUD", new PRD_DESIGNSHARING_CRUD());
            dict.Add("ACCOUNTMASTER_CRUD", new ACCOUNTMASTER_CRUD());
            dict.Add("ACCOUNTMASTER_GET", new ACCOUNTMASTER_GET());
            dict.Add("ACCOUNTMASTERFILES_GET", new ACCOUNTMASTERFILES_GET());
            dict.Add("ACC_QUOTATION_MASTER_CRUD", new ACC_QUOTATION_MASTER_CRUD());
            dict.Add("ACC_JEWELLERYTRANSACTION_MASTER_CRUD", new ACC_JEWELLERYTRANSACTION_MASTER_CRUD());

            dict.Add("PRD_RELATED_DESIGNS_GET", new PRD_RELATED_DESIGNS_GET());
            dict.Add("PRD_SHARED_DESIGNS_GET", new PRD_SHARED_DESIGNS_GET());

            dict.Add("PRD_DEPARTMENT_MASTER_GET", new PRD_DEPARTMENT_MASTER_GET());
            dict.Add("PRD_DEPARTMENT_MASTER_CRUD", new PRD_DEPARTMENT_MASTER_CRUD());

            dict.Add("PRD_DESGCATE_MASTER_GET", new PRD_DESGCATE_MASTER_GET());
            dict.Add("PRD_DESGCATE_MASTER_CRUD", new PRD_DESGCATE_MASTER_CRUD());

            dict.Add("PRD_DESGSUBCATE_MASTER_GET", new PRD_DESGSUBCATE_MASTER_GET());
            dict.Add("PRD_DESGSUBCATE_MASTER_CRUD", new PRD_DESGSUBCATE_MASTER_CRUD());

            dict.Add("PRD_PROCESS_MASTER_GET", new PRD_PROCESS_MASTER_GET());
            dict.Add("PRD_PROCESS_MASTER_CRUD", new PRD_PROCESS_MASTER_CRUD());

            dict.Add("ACC_CURRENCYRATEDIFFERENCE_CRUD", new ACC_CURRENCYRATEDIFFERENCE_CRUD());

            #endregion

            #region "Master"
            dict.Add("ACC_CREDITDEBIT_GET", new ACC_CREDITDEBIT_GET());
            dict.Add("ACC_CREDITDEBIT_CRUD", new ACC_CREDITDEBIT_CRUD());
            dict.Add("ACC_ITEMMASTER_GET", new ACC_ITEMMASTER_GET());
            dict.Add("ACC_ITEMMASTER_CRUD", new ACC_ITEMMASTER_CRUD());
            dict.Add("ACC_ITEMDETAIL_GET", new ACC_ITEMDETAIL_GET());
            dict.Add("ACC_TAX_MASTER_CRUD", new ACC_TAX_MASTER_CRUD());
            dict.Add("ACC_TAX_MASTER_GET", new ACC_TAX_MASTER_GET());
            dict.Add("ACC_TAXPROFILE_CRUD", new ACC_TAXPROFILE_CRUD());
            dict.Add("ACC_TAXPROFILE_GET", new ACC_TAXPROFILE_GET());
            dict.Add("ACC_TAXPROFILE_DETAIL_GET", new ACC_TAXPROFILE_DETAIL_GET());
            #endregion

            dict.Add("PRODUCT_MASTER_GET", new PRODUCT_MASTER_GET());
            dict.Add("PRD_PRODUCT_DETAIL_GET", new PRD_PRODUCT_DETAIL_GET());
            dict.Add("ACC_QUOTATION_MASTER_GET", new ACC_QUOTATION_MASTER_GET());
            dict.Add("ACC_QUOTATION_ITEM_DETAILS_GET", new ACC_QUOTATION_ITEM_DETAILS_GET());
            dict.Add("PRD_DESIGNSHARING_ITEAM_CRUD", new PRD_DESIGNSHARING_ITEAM_CRUD());
            dict.Add("PRD_DESIGNSHARING_ITEAM_GET", new PRD_DESIGNSHARING_ITEAM_GET());
            dict.Add("PRD_SHARINGHISTORY_GET", new PRD_SHARINGHISTORY_GET());
            dict.Add("ACC_CATALOG_TO_QUOTATION_CRUD", new ACC_CATALOG_TO_QUOTATION_CRUD());
            dict.Add("ACC_JEWELLERY_SALE_CRUD", new ACC_JEWELLERY_SALE_CRUD());
            dict.Add("ACC_JEWELLERY_SALE_ITEM_GET", new ACC_JEWELLERY_SALE_ITEM_GET());
            dict.Add("ACC_JEWELLERY_SALE_GET", new ACC_JEWELLERY_SALE_GET());
            dict.Add("ACCOUNTMASTER_SHIPINGINFO_GET", new ACCOUNTMASTER_SHIPINGINFO_GET());
            dict.Add("ACCOUNTMASTER_STAFFINFO_GET", new ACCOUNTMASTER_STAFFINFO_GET());
            dict.Add("ACCOUNTMASTER_OTHERINFO_GET", new ACCOUNTMASTER_OTHERINFO_GET());
            dict.Add("STATIC_ADDRESS_TYPE_GET", new STATIC_ADDRESS_TYPE_GET());
            dict.Add("STATIC_ACCBOOK_MASTER_GET", new STATIC_ACCBOOK_MASTER_GET());
            dict.Add("STATIC_PRICELIST_GET", new STATIC_PRICELIST_GET());
            dict.Add("PRD_SELECTIONLISTITEMS_CART_CRUD", new PRD_SELECTIONLISTITEMS_CART_CRUD());
            dict.Add("PRD_SELECTIONLISTITEMS_CART_GET", new PRD_SELECTIONLISTITEMS_CART_GET());
            dict.Add("ACC_MATERIALTRANSACTION_CRUD", new ACC_MATERIALTRANSACTION_CRUD());
            dict.Add("ACC_MATERIALTRANSACTION_GET", new ACC_MATERIALTRANSACTION_GET());
            dict.Add("ACC_MATERIALTRANSACTION_DETAIL_GET", new ACC_MATERIALTRANSACTION_DETAIL_GET());
            dict.Add("ACC_MATERIAL_STOCK_GET", new ACC_MATERIAL_STOCK_GET());
            dict.Add("ACC_MATERIALTRANSACTION_RETURN_DETAIL_GET", new ACC_MATERIALTRANSACTION_RETURN_DETAIL_GET());
            dict.Add("ACC_MATERIALTRANSACTION_FREIGHTDEATIL_GET", new ACC_MATERIALTRANSACTION_FREIGHTDEATIL_GET());
            dict.Add("JEWELLERY_TRAN_DESIGNLIST_GET", new JEWELLERY_TRAN_DESIGNLIST_GET());
            dict.Add("ACCOUNTMASTER_MACPERMISSION_GET", new ACCOUNTMASTER_MACPERMISSION_GET());
            dict.Add("ACCOUNTMASTER_MACPERMISSION_CRUD", new ACCOUNTMASTER_MACPERMISSION_CRUD());
            dict.Add("ACCOUNTMASTER_REFERENCEDETAILS_GET", new ACCOUNTMASTER_REFERENCEDETAILS_GET());
            dict.Add("ACC_QUOTATION_MATERIAL_RATE_LIST_GET", new ACC_QUOTATION_MATERIAL_RATE_LIST_GET());
            dict.Add("ACC_QUOTATION_DESIGN_DETAILS_GET", new ACC_QUOTATION_DESIGN_DETAILS_GET());

            dict.Add("ACC_ORDER_MASTER_CRUD", new ACC_ORDER_MASTER_CRUD());
            dict.Add("ACC_ORDER_MASTER_GET", new ACC_ORDER_MASTER_GET());
            dict.Add("ACC_ORDER_ITEM_DETAILS_GET", new ACC_ORDER_ITEM_DETAILS_GET());
            dict.Add("ACC_ORDER_DESIGN_DETAILS_GET", new ACC_ORDER_DESIGN_DETAILS_GET());
            dict.Add("ACC_ORDER_MATERIAL_RATE_LIST_GET", new ACC_ORDER_MATERIAL_RATE_LIST_GET());
            dict.Add("ACC_CATALOG_TO_ORDER_CRUD", new ACC_CATALOG_TO_ORDER_CRUD());
            dict.Add("PRD_RMCODE_MASTER_GET", new PRD_RMCODE_MASTER_GET());
            dict.Add("PRD_RMCODE_MASTER_CRUD", new PRD_RMCODE_MASTER_CRUD());
            dict.Add("PRD_RMCATE_MASTER_GET", new PRD_RMCATE_MASTER_GET());
            dict.Add("PRD_RMCATE_MASTER_CRUD", new PRD_RMCATE_MASTER_CRUD());
            dict.Add("PRD_RMSUBCATE_MASTER_GET", new PRD_RMSUBCATE_MASTER_GET());
            dict.Add("PRD_RMSUBCATE_MASTER_CRUD", new PRD_RMSUBCATE_MASTER_CRUD());
            dict.Add("PRD_RMCOLOUR_MASTER_GET", new PRD_RMCOLOUR_MASTER_GET());
            dict.Add("PRD_RMCOLOUR_MASTER_CRUD", new PRD_RMCOLOUR_MASTER_CRUD());
            dict.Add("PRD_RMPURITY_MASTER_GET", new PRD_RMPURITY_MASTER_GET());
            dict.Add("PRD_RMPURITY_MASTER_CRUD", new PRD_RMPURITY_MASTER_CRUD());
            dict.Add("PRD_RMSHAPE_MASTER_GET", new PRD_RMSHAPE_MASTER_GET());
            dict.Add("PRD_RMSHAPE_MASTER_CRUD", new PRD_RMSHAPE_MASTER_CRUD());
            dict.Add("PRD_RMCUT_MASTER_GET", new PRD_RMCUT_MASTER_GET());
            dict.Add("PRD_RMCUT_MASTER_CRUD", new PRD_RMCUT_MASTER_CRUD());
            dict.Add("LOCKERMASTER_GET", new LOCKERMASTER_GET());
            dict.Add("LOCKERMASTER_CRUD", new LOCKERMASTER_CRUD());
            dict.Add("ACC_PENDING_VOUCHER_GET", new ACC_PENDING_VOUCHER_GET());
            dict.Add("ACC_JEWELLERYTRANSACTION_ITEMS_LIST_GET", new ACC_JEWELLERYTRANSACTION_ITEMS_LIST_GET());
            dict.Add("ACC_JEWELLERYTRANSACTION_MASTER_GET", new ACC_JEWELLERYTRANSACTION_MASTER_GET());
            dict.Add("ACC_JEWELLERYTRANSACTION_DESIGN_DETAILS_GET", new ACC_JEWELLERYTRANSACTION_DESIGN_DETAILS_GET());
            dict.Add("ACC_JEWELLERY_MATERIAL_RATE_LIST_GET", new ACC_JEWELLERY_MATERIAL_RATE_LIST_GET());
            dict.Add("ACC_CASHBANK_TRANSACTION_GET", new ACC_CASHBANK_TRANSACTION_GET());
            dict.Add("ACC_CASHBANK_TRANSACTION_CRUD", new ACC_CASHBANK_TRANSACTION_CRUD());
            dict.Add("ACC_MATERIALTRANSACTION_FILESLIST_GET", new ACC_MATERIALTRANSACTION_FILESLIST_GET());
            dict.Add("ACC_JEWELLERYTRANSACTION_FILESLIST_GET", new ACC_JEWELLERYTRANSACTION_FILESLIST_GET());
            dict.Add("ACC_CASHBANKBOOK_DETAILS_GET", new ACC_CASHBANKBOOK_DETAILS_GET());
            dict.Add("PRD_PRODUCT_MASTER_GET", new PRD_PRODUCT_MASTER_GET());
            dict.Add("ACC_CONTRAENTRY_CRUD", new ACC_CONTRAENTRY_CRUD());
            dict.Add("ACC_CATALOG_TO_SALE_CRUD", new ACC_CATALOG_TO_SALE_CRUD());
            dict.Add("ACC_GENERALEXPENSE_GET", new ACC_GENERALEXPENSE_GET());
            dict.Add("ACC_GENERALEXPANSE_CRUD", new ACC_GENERALEXPANSE_CRUD());
            dict.Add("ACC_CONTRA_CHARGE_DETAIL_GET", new ACC_CONTRA_CHARGE_DETAIL_GET());
            dict.Add("ACC_GENERALEXPANSE_FILES_GET", new ACC_GENERALEXPANSE_FILES_GET());
            dict.Add("ACC_GENERALEXPANSE_DETAIL_GET", new ACC_GENERALEXPANSE_DETAIL_GET());
            dict.Add("COMPANYMASTER_FILES_GET", new COMPANYMASTER_FILES_GET());
            dict.Add("USERACCESSGROUPS_PERMISSION_GET", new USERACCESSGROUPS_PERMISSION_GET());
            dict.Add("ACC_ACCOUNTOPENINGBALANCE_GET", new ACC_ACCOUNTOPENINGBALANCE_GET());
            dict.Add("ACC_ACCOUNTOPENINGBALANCE_CRUD", new ACC_ACCOUNTOPENINGBALANCE_CRUD());
            dict.Add("ACC_JOURNAL_MASTER_GET", new ACC_JOURNAL_MASTER_GET());
            dict.Add("ACC_JOURNAL_MASTER_CRUD", new ACC_JOURNAL_MASTER_CRUD());
            dict.Add("ACC_SALEPURCHASEJV_DETAIL_GET", new ACC_SALEPURCHASEJV_DETAIL_GET());
            dict.Add("ACC_SALEPURCHASEJV_GET", new ACC_SALEPURCHASEJV_GET());
            dict.Add("ACC_SALEPURCHASEJV_CRUD", new ACC_SALEPURCHASEJV_CRUD());
            dict.Add("ACC_HEAD_MASTER_GET", new ACC_HEAD_MASTER_GET());
            dict.Add("ACC_HEAD_MASTER_CRUD", new ACC_HEAD_MASTER_CRUD());
            dict.Add("ACC_SUBHEAD_MASTER_GET", new ACC_SUBHEAD_MASTER_GET());
            dict.Add("ACC_SUBHEAD_MASTER_CRUD", new ACC_SUBHEAD_MASTER_CRUD());
            dict.Add("PRD_DESIGNTREE_MASTER_GET", new PRD_DESIGNTREE_MASTER_GET());
            dict.Add("COMMON_MENUMAS_GET", new COMMON_MENUMAS_GET());
            dict.Add("ACC_CREDITDEBITNOTE_GET", new ACC_CREDITDEBITNOTE_GET());
            dict.Add("ACC_CREDITDEBITNOTE_CRUD", new ACC_CREDITDEBITNOTE_CRUD());
            dict.Add("BRANCHMASTER_FILES_GET", new BRANCHMASTER_FILES_GET());

            dict.Add("ACC_SALARYDETAILS_GET", new ACC_SALARYDETAILS_GET());
            dict.Add("ACC_SALARY_MASTER_GET", new ACC_SALARY_MASTER_GET()); 
            dict.Add("ACC_SALARY_MASTER_CRUD", new ACC_SALARY_MASTER_CRUD()); 
            dict.Add("ACC_CONTRA_CHARGE_AMT_GET", new ACC_CONTRA_CHARGE_AMT_GET());
            dict.Add("ACC_Change_Password_CRUD", new ACC_Change_Password_CRUD());
            dict.Add("ACC_VOUCHER_SIGNATURE_CRUD", new ACC_VOUCHER_SIGNATURE_CRUD());

            dict.Add("ACC_CASHBANKBOOK_PRINT_GET", new ACC_CASHBANKBOOK_PRINT_GET());
            dict.Add("ACC_GENERALEXPENSE_PRINT_GET", new ACC_GENERALEXPENSE_PRINT_GET());
            dict.Add("ACC_JEWELLERYTRANSACTION_PRINT_GET", new ACC_JEWELLERYTRANSACTION_PRINT_GET());
            dict.Add("ACC_MIX_EXPORT_PRINT_GET", new ACC_MIX_EXPORT_PRINT_GET());
            dict.Add("ACC_MATERIAL_EXPORT_PRINT_GET", new ACC_MATERIAL_EXPORT_PRINT_GET());
            dict.Add("ACC_MATERIALTRANSACTION_PRINT_GET", new ACC_MATERIALTRANSACTION_PRINT_GET());
            dict.Add("ACC_ORDERMASTER_PRINT_GET", new ACC_ORDERMASTER_PRINT_GET());
            dict.Add("ACC_QUOTATIONMASTER_PRINT_GET", new ACC_QUOTATIONMASTER_PRINT_GET());
            dict.Add("ACC_FORGOTPASSWORD_OTP_GET", new ACC_FORGOTPASSWORD_OTP_GET());
            dict.Add("ACC_VERIFY_OTP", new ACC_VERIFY_OTP());
            dict.Add("ACC_RESET_PASSWORD", new ACC_RESET_PASSWORD());

            /*---Year End Process--------------------------------------------------------------------------------------------*/
            dict.Add("YEARENDPROCESS_ACCOUNTLIST_GET", new YEARENDPROCESS_ACCOUNTLIST_GET()); 
            dict.Add("ACC_YEARENDPROCESS_GET", new ACC_YEARENDPROCESS_GET()); 
            dict.Add("ACC_ACCOUNTYEAR_CLOSEPERIOD_GET", new ACC_ACCOUNTYEAR_CLOSEPERIOD_GET());
            dict.Add("ACC_ACCOUNTYEAR_CLOSEPERIOD_CRUD", new ACC_ACCOUNTYEAR_CLOSEPERIOD_CRUD());
            /*-----------------------------------------------------------------------------------------------*/
            dict.Add("ACC_MATERIAL_PRICEMASTER_GET", new ACC_MATERIAL_PRICEMASTER_GET());
            dict.Add("ACC_MATERIAL_PRICELIST_GET", new ACC_MATERIAL_PRICELIST_GET());
            dict.Add("ACC_MATERIAL_PRICEMASTER_CRUD", new ACC_MATERIAL_PRICEMASTER_CRUD());
            dict.Add("ACC_MATERIAL_PRICELIST_CRUD", new ACC_MATERIAL_PRICELIST_CRUD());
            dict.Add("ACC_LABOUR_PRICEMASTER_GET", new ACC_LABOUR_PRICEMASTER_GET()); 
            dict.Add("ACC_LABOUR_PRICELIST_GET", new ACC_LABOUR_PRICELIST_GET()); 
            dict.Add("ACC_LABOUR_PRICEMASTER_CRUD", new ACC_LABOUR_PRICEMASTER_CRUD());
            dict.Add("ACC_LABOUR_PRICELIST_CRUD", new ACC_LABOUR_PRICELIST_CRUD());
            dict.Add("JEWELLERY_EINVOICEBILL_CRUD", new JEWELLERY_EINVOICEBILL_CRUD()); 
            dict.Add("JEWELLERY_EINVOICEBILL_CANCLE_CRUD", new JEWELLERY_EINVOICEBILL_CANCLE_CRUD());
            dict.Add("JEWELLERY_EINVOICEBILL_UPDATE_CRUD", new JEWELLERY_EINVOICEBILL_UPDATE_CRUD()); 
            dict.Add("MATERIAL_EINVOICEBILL_CRUD", new MATERIAL_EINVOICEBILL_CRUD()); 
            dict.Add("MATERIAL_EINVOICEBILL_CANCLE_CRUD", new MATERIAL_EINVOICEBILL_CANCLE_CRUD()); 
            dict.Add("MATERIAL_EINVOICEBILL_UPDATE_CRUD", new MATERIAL_EINVOICEBILL_UPDATE_CRUD());
            dict.Add("ACC_CASHBANK_BANK_REPORT_GET", new ACC_CASHBANK_BANK_REPORT_GET()); 
            dict.Add("ACC_CASHBANK_CASH_REPORT_GET", new ACC_CASHBANK_CASH_REPORT_GET()); 
            dict.Add("ACC_CASHBANK_REPORT_DETAILS_GET", new ACC_CASHBANK_REPORT_DETAILS_GET()); 


        }

        public static ICommon ExecuteMethod(string methodName)
        {
            return dict[methodName];
        }
    }
}